spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fitsphere?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring Security Config (Basic setup to allow access to console/endpoints initially)
spring.security.user.name=admin
spring.security.user.password=admin
